spring.application.name=musichub

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/musichub
spring.datasource.username=postgres
spring.datasource.password=Mayank@13579

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8080